<?php

/**
 * This is the model base class for the table "ClientsShops".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ClientsShops".
 *
 * Columns in table "ClientsShops" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $createdAt
 * @property string $updatedAt
 * @property integer $ShopId
 * @property integer $ClientId
 *
 */
abstract class BaseClientsShops extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ClientsShops';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ClientsShops|ClientsShops', $n);
	}

	public static function representingColumn() {
		return 'createdAt';
	}

	public function rules() {
		return array(
			array('createdAt, updatedAt', 'required'),
			array('ShopId, ClientId', 'numerical', 'integerOnly'=>true),
			array('ShopId, ClientId', 'default', 'setOnEmpty' => true, 'value' => null),
			array('createdAt, updatedAt, ShopId, ClientId', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'createdAt' => Yii::t('app', 'Created At'),
			'updatedAt' => Yii::t('app', 'Updated At'),
			'ShopId' => Yii::t('app', 'Shop'),
			'ClientId' => Yii::t('app', 'Client'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('createdAt', $this->createdAt, true);
		$criteria->compare('updatedAt', $this->updatedAt, true);
		$criteria->compare('ShopId', $this->ShopId);
		$criteria->compare('ClientId', $this->ClientId);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}