<?php

/**
 * This is the model base class for the table "OrderLine".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OrderLine".
 *
 * Columns in table "OrderLine" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $product_code
 * @property string $product_name
 * @property string $price
 * @property string $date_add
 * @property string $date_update
 * @property integer $order_id
 *
 */
abstract class BaseOrderLine extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'OrderLine';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OrderLine|OrderLines', $n);
	}

	public static function representingColumn() {
		return 'product_code';
	}

	public function rules() {
		return array(
			array('order_id', 'required'),
			array('order_id', 'numerical', 'integerOnly'=>true),
			array('product_code', 'length', 'max'=>200),
			array('product_name', 'length', 'max'=>1024),
			array('price', 'length', 'max'=>17),
			array('date_add, date_update', 'safe'),
			array('product_code, product_name, price, date_add, date_update', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, product_code, product_name, price, date_add, date_update, order_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'product_code' => Yii::t('app', 'Product Code'),
			'product_name' => Yii::t('app', 'Product Name'),
			'price' => Yii::t('app', 'Price'),
			'date_add' => Yii::t('app', 'Date Add'),
			'date_update' => Yii::t('app', 'Date Update'),
			'order_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('product_code', $this->product_code, true);
		$criteria->compare('product_name', $this->product_name, true);
		$criteria->compare('price', $this->price, true);
		$criteria->compare('date_add', $this->date_add, true);
		$criteria->compare('date_update', $this->date_update, true);
		$criteria->compare('order_id', $this->order_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}