<?php

/**
 * This is the model base class for the table "Opinion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Opinion".
 *
 * Columns in table "Opinion" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $description
 * @property integer $rating
 * @property string $date
 * @property string $date_add
 * @property string $date_update
 * @property integer $order_id
 * @property string $lang
 *
 */
abstract class BaseOpinion extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Opinion';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Opinion|Opinions', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('order_id', 'required'),
			array('rating, order_id', 'numerical', 'integerOnly'=>true),
			array('description', 'length', 'max'=>4000),
			array('lang', 'length', 'max'=>3),
			array('date, date_add, date_update', 'safe'),
			array('description, rating, date, date_add, date_update, lang', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, description, rating, date, date_add, date_update, order_id, lang', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'description' => Yii::t('app', 'Description'),
			'rating' => Yii::t('app', 'Rating'),
			'date' => Yii::t('app', 'Date'),
			'date_add' => Yii::t('app', 'Date Add'),
			'date_update' => Yii::t('app', 'Date Update'),
			'order_id' => null,
			'lang' => Yii::t('app', 'Lang'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('rating', $this->rating);
		$criteria->compare('date', $this->date, true);
		$criteria->compare('date_add', $this->date_add, true);
		$criteria->compare('date_update', $this->date_update, true);
		$criteria->compare('order_id', $this->order_id);
		$criteria->compare('lang', $this->lang, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}