<?php

/**
 * This is the model base class for the table "Order".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Order".
 *
 * Columns in table "Order" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $description
 * @property string $date
 * @property string $token
 * @property string $date_add
 * @property string $date_update
 * @property integer $pending
 * @property integer $customer_id
 * @property integer $Shop_user_id
 *
 */
abstract class BaseOrder extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Order';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Order|Orders', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('customer_id, Shop_user_id', 'required'),
			array('pending, customer_id, Shop_user_id', 'numerical', 'integerOnly'=>true),
			array('description', 'length', 'max'=>1024),
			array('token', 'length', 'max'=>45),
			array('date, date_add, date_update', 'safe'),
			array('description, date, token, date_add, date_update, pending', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, description, date, token, date_add, date_update, pending, customer_id, Shop_user_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'description' => Yii::t('app', 'Description'),
			'date' => Yii::t('app', 'Date'),
			'token' => Yii::t('app', 'Token'),
			'date_add' => Yii::t('app', 'Date Add'),
			'date_update' => Yii::t('app', 'Date Update'),
			'pending' => Yii::t('app', 'Pending'),
			'customer_id' => null,
			'Shop_user_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('date', $this->date, true);
		$criteria->compare('token', $this->token, true);
		$criteria->compare('date_add', $this->date_add, true);
		$criteria->compare('date_update', $this->date_update, true);
		$criteria->compare('pending', $this->pending);
		$criteria->compare('customer_id', $this->customer_id);
		$criteria->compare('Shop_user_id', $this->Shop_user_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}