<?php

/**
 * This is the model base class for the table "Clients".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Clients".
 *
 * Columns in table "Clients" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $surname
 * @property string $address
 * @property string $city
 * @property string $post_code
 * @property string $country
 * @property string $born_date
 * @property string $sex
 * @property string $email
 * @property string $phone
 * @property string $clientcol
 * @property string $createdAt
 * @property string $updatedAt
 * @property integer $OrderId
 *
 */
abstract class BaseClients extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Clients';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Clients|Clients', $n);
	}

	public static function representingColumn() {
		return 'createdAt';
	}

	public function rules() {
		return array(
			array('createdAt, updatedAt', 'required'),
			array('OrderId', 'numerical', 'integerOnly'=>true),
			array('name, surname, city, country, email', 'length', 'max'=>255),
			array('address', 'length', 'max'=>512),
			array('post_code', 'length', 'max'=>10),
			array('sex', 'length', 'max'=>1),
			array('phone, clientcol', 'length', 'max'=>45),
			array('born_date', 'safe'),
			array('name, surname, address, city, post_code, country, born_date, sex, email, phone, clientcol, OrderId', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, surname, address, city, post_code, country, born_date, sex, email, phone, clientcol, createdAt, updatedAt, OrderId', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'surname' => Yii::t('app', 'Surname'),
			'address' => Yii::t('app', 'Address'),
			'city' => Yii::t('app', 'City'),
			'post_code' => Yii::t('app', 'Post Code'),
			'country' => Yii::t('app', 'Country'),
			'born_date' => Yii::t('app', 'Born Date'),
			'sex' => Yii::t('app', 'Sex'),
			'email' => Yii::t('app', 'Email'),
			'phone' => Yii::t('app', 'Phone'),
			'clientcol' => Yii::t('app', 'Clientcol'),
			'createdAt' => Yii::t('app', 'Created At'),
			'updatedAt' => Yii::t('app', 'Updated At'),
			'OrderId' => Yii::t('app', 'Order'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('surname', $this->surname, true);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('city', $this->city, true);
		$criteria->compare('post_code', $this->post_code, true);
		$criteria->compare('country', $this->country, true);
		$criteria->compare('born_date', $this->born_date, true);
		$criteria->compare('sex', $this->sex, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('phone', $this->phone, true);
		$criteria->compare('clientcol', $this->clientcol, true);
		$criteria->compare('createdAt', $this->createdAt, true);
		$criteria->compare('updatedAt', $this->updatedAt, true);
		$criteria->compare('OrderId', $this->OrderId);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}